version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - BACKEND_URL=http://backend:8080/api
    networks:
      - reader_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - SECRET=${SECRET}
      - PORT=8080
    networks:
      - reader_network
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - reader_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - reader_network
    command: server /data

networks:
  reader_network:
